### ISSUE TITLE
Add bytes interface

### ISSUE THREAD

**Issue by Alphare** [bmwill/diffy#1]
Hello there!

I saw in your reddit announcement post that "For right now the library only operates on utf8 strings but it shouldn't be too much work to also handle non-utf8 input (which would be needed if this was to actually be used in a VCS)", which I definitely agree with, so I thought I would open this issue to encourage the bytes API as a fully-supported interface. 

Thanks for building this diffing tool.

**Comment by bmwill** [comment]
Thanks for your interest!

Really the only question that needs to be answered before exposing a bytes API is how to handle the differing types `str` vs `[u8]`. I can see two different options (there may be others):
1. Simply have different types `Patch` and `PatchBytes`, the downside is that this leads to having a larger number of types.
2. Make `Patch` and friends have a generic parameter so you end up with `Patch<str>` and `Patch<[u8]>`, perhaps making one of those a default generic parameter.
